### ISSUE TITLE
NodeJS cross-env issues

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#31]
`cross-env.js` will often kick an error; this happens for me on both Mac and Windows:

```bash
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn node_modules/webpack/bin/webpack.js',
  path: 'node_modules/webpack/bin/webpack.js',
  spawnargs: [
    '--progress',
    '--hide-modules',
    '--config=node_modules/laravel-mix/setup/webpack.config.js',
    '--watch'
  ]
}
```

Unfortunately, the many suggestions given by Google haven't worked consistently for me. However, as a temporary work around, you can build directly, at least on Mac:

`NODE_ENV=development node node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`

**Comment by joshreisner** [comment]
This hasn't happened to me yet. Delete node_modules and do an npm install and I think it should be fine.
